# Generated by Django 6.0 on 2026-01-08 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SheetMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(db_index=True, max_length=100)),
                ('headers', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(db_index=True, max_length=100)),
                ('sl_no', models.CharField(blank=True, db_index=True, max_length=50)),
                ('sw_part_number', models.CharField(blank=True, db_index=True, max_length=200)),
                ('feature', models.TextField(blank=True)),
                ('requirement_id', models.CharField(blank=True, max_length=200, verbose_name='Requirement ID')),
                ('app_sw_version', models.CharField(blank=True, db_index=True, help_text='Application Software Version', max_length=100)),
                ('requirement_description', models.TextField(blank=True)),
                ('base_test_case_id', models.CharField(db_index=True, help_text='Original test case ID from Excel (without version suffix)', max_length=200)),
                ('test_case_id', models.CharField(db_index=True, help_text='Versioned test case ID (base_test_case_id + version suffix)', max_length=200)),
                ('test_case_summary', models.TextField(blank=True)),
                ('pre_conditions', models.TextField(blank=True)),
                ('inputs', models.TextField(blank=True)),
                ('periodic_time', models.CharField(blank=True, max_length=100)),
                ('test_steps', models.TextField(blank=True)),
                ('expected_result', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, db_index=True, help_text='Design / specification status only (NOT execution result)', max_length=100)),
                ('reports', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TestCaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_part_number', models.CharField(db_index=True, max_length=200)),
                ('app_sw_version', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one active version per SW part number should exist')),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Locked versions are read-only for everyone')),
                ('execution_status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved')], db_index=True, default='NOT_STARTED', help_text='Final execution status of this version. APPROVED versions are immutable.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Test Case Version',
                'verbose_name_plural': 'Test Case Versions',
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ADD', 'Add'), ('EDIT', 'Edit'), ('IMPORT', 'Import'), ('LOGOUT', 'Logout')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('content_type', models.CharField(blank=True, help_text='TestCase / SheetMeta / System', max_length=50)),
                ('diff', models.JSONField(blank=True, help_text='Stores old → new field values', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestCaseSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheets', to='testmanager.testcaseversion')),
            ],
            options={
                'verbose_name': 'Test Case Sheet',
                'verbose_name_plural': 'Test Case Sheets',
            },
        ),
        migrations.CreateModel(
            name='TestInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one instance should be active at a time')),
            ],
            options={
                'verbose_name': 'Test Instance',
                'verbose_name_plural': 'Test Instances',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='testmanager_is_acti_966f57_idx'), models.Index(fields=['-created_at'], name='testmanager_created_be8e60_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestExecutionSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_id', models.CharField(blank=True, db_index=True, help_text='Unique export identifier (e.g., export_1, export_2)', max_length=50, null=True, unique=True)),
                ('snapshot_name', models.CharField(db_index=True, help_text='Name/version of this snapshot', max_length=200)),
                ('sheet_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('sw_part_number', models.CharField(blank=True, db_index=True, max_length=200)),
                ('app_sw_version', models.CharField(blank=True, db_index=True, max_length=100)),
                ('execution_data', models.JSONField(default=list, help_text='List of test execution records at time of export')),
                ('exported_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_test_cases', models.IntegerField(default=0)),
                ('total_executed', models.IntegerField(default=0)),
                ('total_passed', models.IntegerField(default=0)),
                ('total_failed', models.IntegerField(default=0)),
                ('total_not_executed', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this export')),
                ('exported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_snapshots', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(blank=True, help_text='The test instance this snapshot belongs to (null for old snapshots)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='testmanager.testinstance')),
            ],
            options={
                'verbose_name': 'Test Execution Snapshot',
                'verbose_name_plural': 'Test Execution Snapshots',
                'ordering': ['-exported_at'],
            },
        ),
        migrations.CreateModel(
            name='TestExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_part_number', models.CharField(db_index=True, max_length=200)),
                ('app_sw_version', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(blank=True, db_index=True, max_length=100)),
                ('reports', models.TextField(blank=True)),
                ('comments', models.TextField(blank=True)),
                ('executed_at', models.DateTimeField(auto_now=True)),
                ('manager_approved', models.BooleanField(db_index=True, default=False, help_text='Manager approval that test is completed')),
                ('approved_at', models.DateTimeField(blank=True, help_text='When manager approved this test', null=True)),
                ('is_locked', models.BooleanField(db_index=True, default=False, help_text='Locked executions are read-only for everyone')),
                ('approved_by', models.ForeignKey(blank=True, help_text='Manager who approved this test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_executions', to=settings.AUTH_USER_MODEL)),
                ('sheet', models.ForeignKey(blank=True, help_text='The sheet this execution belongs to (explicit FK)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testmanager.testcasesheet')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testmanager.testcase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='The version this execution belongs to (explicit FK)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testmanager.testcaseversion')),
                ('instance', models.ForeignKey(blank=True, help_text='The test instance this execution belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='testmanager.testinstance')),
            ],
            options={
                'ordering': ['test_case__id'],
            },
        ),
        migrations.AddField(
            model_name='testcaseversion',
            name='instance',
            field=models.ForeignKey(blank=True, help_text='The test instance this version belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_case_versions', to='testmanager.testinstance'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='instance',
            field=models.ForeignKey(blank=True, help_text='The test instance this test case belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='testmanager.testinstance'),
        ),
        migrations.CreateModel(
            name='SWVersionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sw_part_number', models.CharField(db_index=True, max_length=200)),
                ('version', models.CharField(db_index=True, max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Only one version per SW part number should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(blank=True, help_text='The test instance this version mapping belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='version_mappings', to='testmanager.testinstance')),
            ],
            options={
                'verbose_name': 'SW Version Mapping',
                'verbose_name_plural': 'SW Version Mappings',
                'ordering': ['sw_part_number'],
            },
        ),
        migrations.CreateModel(
            name='ProjectOverview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software_part_number', models.CharField(blank=True, db_index=True, help_text='Software Part Number', max_length=200)),
                ('application_sw_version', models.CharField(blank=True, db_index=True, help_text='Application SW Version', max_length=100)),
                ('sw_part_number', models.CharField(blank=True, db_index=True, max_length=200)),
                ('app_sw_version', models.CharField(blank=True, db_index=True, max_length=100)),
                ('key', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('value', models.TextField(blank=True)),
                ('sheet_name', models.CharField(blank=True, db_index=True, max_length=100)),
                ('overview_text', models.TextField(blank=True, help_text='Legacy overview text field')),
                ('project_code', models.CharField(blank=True, help_text='Project Code', max_length=200)),
                ('vcu_platform', models.CharField(blank=True, help_text='VCU Platform', max_length=200)),
                ('hardware_part_number', models.CharField(blank=True, help_text='Hardware Part Number', max_length=200)),
                ('project_stage', models.CharField(blank=True, help_text='Project Stage', max_length=200)),
                ('developer', models.CharField(blank=True, help_text='Developer', max_length=200)),
                ('test_engineer', models.CharField(blank=True, help_text='Test Engineer', max_length=200)),
                ('bootloader_sw_version', models.CharField(blank=True, help_text='Bootloader SW Version', max_length=200)),
                ('checksum_value', models.CharField(blank=True, help_text='Checksum Value', max_length=200)),
                ('dbc_test_it', models.TextField(blank=True, help_text='DBC test_it (file link or text reference)')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this project overview', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_project_overviews', to=settings.AUTH_USER_MODEL)),
                ('version', models.ForeignKey(blank=True, help_text='The version this project overview belongs to (explicit FK)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_overviews', to='testmanager.testcaseversion')),
                ('instance', models.ForeignKey(blank=True, help_text='The test instance this project overview belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_overviews', to='testmanager.testinstance')),
            ],
            options={
                'verbose_name': 'Project Overview',
                'verbose_name_plural': 'Project Overviews',
                'ordering': ['-updated_at'],
                'permissions': [('edit_project_overview', 'Can edit project overview')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Employee ID')),
                ('full_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('role', models.CharField(choices=[('Tester', 'Tester'), ('Test Engineer', 'Test Engineer'), ('Developer', 'Developer'), ('Manager', 'Manager')], max_length=50, verbose_name='Role')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'ordering': ['full_name'],
            },
        ),
        migrations.AddIndex(
            model_name='testcasesheet',
            index=models.Index(fields=['version', 'sheet_name'], name='testmanager_version_09e0a2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testcasesheet',
            unique_together={('version', 'sheet_name')},
        ),
        migrations.AddIndex(
            model_name='testexecutionsnapshot',
            index=models.Index(fields=['sheet_name', 'sw_part_number', 'app_sw_version'], name='testmanager_sheet_n_265e95_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecutionsnapshot',
            index=models.Index(fields=['-exported_at'], name='testmanager_exporte_77f047_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecutionsnapshot',
            index=models.Index(fields=['export_id'], name='testmanager_export__5c1925_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['instance', 'test_case', 'version', 'sheet'], name='testmanager_instanc_463267_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['-executed_at'], name='testmanager_execute_79da21_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['manager_approved'], name='testmanager_manager_400de0_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['is_locked'], name='testmanager_is_lock_6ee9e8_idx'),
        ),
        migrations.AddIndex(
            model_name='testexecution',
            index=models.Index(fields=['instance'], name='testmanager_instanc_cf7b0e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testexecution',
            unique_together={('instance', 'test_case', 'version', 'sheet')},
        ),
        migrations.AddIndex(
            model_name='testcaseversion',
            index=models.Index(fields=['instance', 'sw_part_number', 'is_active'], name='testmanager_instanc_e48432_idx'),
        ),
        migrations.AddIndex(
            model_name='testcaseversion',
            index=models.Index(fields=['is_locked'], name='testmanager_is_lock_a1ea75_idx'),
        ),
        migrations.AddIndex(
            model_name='testcaseversion',
            index=models.Index(fields=['execution_status'], name='testmanager_executi_6e7ab7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='testcaseversion',
            unique_together={('instance', 'sw_part_number', 'app_sw_version')},
        ),
        migrations.AlterUniqueTogether(
            name='testcase',
            unique_together={('instance', 'base_test_case_id', 'app_sw_version')},
        ),
        migrations.AlterUniqueTogether(
            name='swversionmapping',
            unique_together={('instance', 'sw_part_number')},
        ),
        migrations.AddIndex(
            model_name='projectoverview',
            index=models.Index(fields=['version'], name='testmanager_version_8bbda0_idx'),
        ),
        migrations.AddIndex(
            model_name='projectoverview',
            index=models.Index(fields=['instance', 'software_part_number', 'application_sw_version'], name='testmanager_instanc_4a9446_idx'),
        ),
        migrations.AddIndex(
            model_name='projectoverview',
            index=models.Index(fields=['-updated_at'], name='testmanager_updated_2bdc72_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='projectoverview',
            unique_together={('version',)},
        ),
    ]
