# testmanager/urls.py
from django.urls import path
from . import views
from .views import custom_logout

urlpatterns = [
    path('', views.home, name='home'),
    path("login/redirect/", views.post_login_redirect, name="post_login_redirect"),
    path("project-overview/get/", views.get_project_overview, name="get_project_overview"),
    path("project-overview/save/", views.save_project_overview, name="save_project_overview"),
    path('testcases/', views.testcase_list, name='testcase_list'),
    path("create-testcases/", views.create_testcases, name="create_testcases"),
    path("create-new-version/", views.create_new_version, name="create_new_version"),
    path('testcases/add/', views.testcase_add, name='testcase_add'),
    path('testcases/<int:id>/', views.testcase_test_it, name='testcase_test_it'),
    path('view/<int:id>/', views.view_test_execution, name='view_test_execution'),
    path('upload/', views.upload_excel, name='upload_excel'),
    path('upload/input-versions/', views.input_versions, name='input_versions'),
    path('upload/import/', views.import_excel, name='import_excel'),
    path("export/sheets/", views.get_sheets_api, name="get_sheets_api"),
    path("export/versions/", views.get_versions_for_sheet_api, name="get_versions_for_sheet_api"),
    path("export/features/", views.get_features_for_selection_api, name="get_features_for_selection_api"),
    path("export/completed-features/", views.get_completed_features_for_sw_api, name="get_completed_features_for_selection_api"),
    path("create-instance/sw-part-numbers/", views.get_sw_part_numbers_for_sheet_api, name="get_sw_part_numbers_for_sheet_api"),
    path("create-instance/completed-features/", views.get_completed_features_for_sw_api, name="get_completed_features_for_sw_api"),
    path("export/", views.export_excel, name="export_excel"),
    path("export/html/", views.export_html, name="export_html"),
    path("export/html/<str:export_id>/", views.export_html_snapshot, name="export_html_snapshot"),
    path("reset-execution-data/", views.reset_execution_data, name="reset_execution_data"),
    path("create-new-test-instance/", views.create_new_test_instance, name="create_new_test_instance"),
    path("api/feature-completion-status/", views.get_feature_completion_status_api, name="get_feature_completion_status_api"),
    path("api/next-sl-no/", views.get_next_sl_no_api, name="get_next_sl_no_api"),
    path("toggle-tested-status/", views.toggle_tested_status, name="toggle_tested_status"),
    path("logout/", custom_logout, name="custom_logout"),
    path("project-overview/update/", views.update_project_overview, name="update_project_overview"),
    path("history/", views.history, name="history"),
    path("admin-page/", views.admin_page, name="admin_page"),
    path("admin-page/create-user/", views.create_user, name="create_user"),
    path("instruction/", views.instruction_page, name="instruction"),
]
